
from pathlib import Path
import json
import numpy as np
import matplotlib.pyplot as plt

from fu_models import FuParameters, FuReducedModel, FullMultiVSC

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs"
OUT.mkdir(exist_ok=True)


def phase_background(ax, model, delta_min=-2*np.pi/5, delta_max=np.pi):
    q = model.quantities()
    delta = np.linspace(delta_min, delta_max, 520)
    omega = np.linspace(-200.0, 200.0, 440)
    DD, WW = np.meshgrid(delta, omega)
    W = model.energy(DD, WW)
    Wdot_wc = model.worst_case_wdot(DD, WW)

    levels = np.linspace(
        np.nanpercentile(W, 2),
        np.nanpercentile(W, 82),
        18,
    )
    ax.contour(DD, WW, W, levels=levels, linewidths=0.8)

    # Hatched set: worst-case non-dissipative region, Wdot_wc > 0.
    ax.contourf(
        DD,
        WW,
        (Wdot_wc > 0).astype(float),
        levels=[0.5, 1.5],
        alpha=0.22,
        hatches=["///"],
    )

    ax.scatter([q["delta_sep"], q["delta_uep"]], [0, 0], s=28)
    ax.annotate("SEP", (q["delta_sep"], 0), xytext=(5, 8), textcoords="offset points")
    ax.annotate("UEP", (q["delta_uep"], 0), xytext=(5, 8), textcoords="offset points")
    ax.set_xlim(delta_min, delta_max)
    ax.set_ylim(-200, 200)
    ax.set_xlabel(r"$\delta$ [rad]")
    ax.set_ylabel(r"$\Delta\omega$ [rad/s]")
    return q


def save_fig(fig, filename):
    fig.tight_layout()
    fig.savefig(OUT / filename, dpi=220, bbox_inches="tight")
    plt.close(fig)


def run():
    p = FuParameters()
    summary = {}

    # 1) Paper Fig. 6 style reconstruction.
    m_fig6 = FuReducedModel(
        p=p,
        static_scale=1.5,
        dynamic_bound_scale=0.3,
        b1=p.B1_identical_neighbor,
    )
    fig, ax = plt.subplots()
    q6 = phase_background(ax, m_fig6)
    ax.set_title("Fu Fig. 6-style reconstruction: energy contours and non-dissipative set")
    ax.text(
        0.02,
        0.02,
        "Hatching: worst-case $\\dot W>0$ under bounded dynamic interaction",
        transform=ax.transAxes,
        fontsize=8,
    )
    save_fig(fig, "01_fig6_style_non_dissipative_region.png")
    summary["fig6_reduced"] = {k: float(v) for k, v in q6.items()}

    # 2) Single VSC: current-loop/PLL coupling, with and without voltage feedforward.
    single_ff = FullMultiVSC(1)
    single_ff.voltage_feedforward[:] = 1.0
    res_ff = single_ff.simulate_fault(depth=0.5, duration=0.04)

    single_noff = FullMultiVSC(1)
    single_noff.voltage_feedforward[:] = 0.0
    res_noff = single_noff.simulate_fault(depth=0.5, duration=0.04)

    m_single = FuReducedModel(
        p=p,
        static_scale=1.0,
        dynamic_bound_scale=0.6,
        b1=0.0,
    )
    fig, ax = plt.subplots()
    phase_background(ax, m_single)
    ax.plot(res_ff["x"][1, :], res_ff["omega"][:, 0], label="voltage feedforward")
    ax.plot(res_noff["x"][1, :], res_noff["omega"][:, 0], label="no voltage feedforward")
    ax.scatter(
        [res_ff["x"][1, 0], res_noff["x"][1, 0]],
        [res_ff["omega"][0, 0], res_noff["omega"][0, 0]],
        marker="x",
        s=36,
    )
    ax.set_title("Inner current-loop–PLL coupling: projected phase trajectories")
    ax.legend()
    save_fig(fig, "02_single_vsc_inner_outer_coupling_phase.png")

    fig, ax = plt.subplots()
    ax.plot(res_ff["t"], res_ff["delta_A"][:, 0] / p.A, label="voltage feedforward")
    ax.plot(res_noff["t"], res_noff["delta_A"][:, 0] / p.A, label="no voltage feedforward")
    ax.axhline(0.0, linewidth=0.8)
    ax.set_xlabel("time [s]")
    ax.set_ylabel(r"$\Delta A_1/A_1$")
    ax.set_title("Dynamic interaction generated by the inner current loop")
    ax.legend()
    save_fig(fig, "03_single_vsc_dynamic_interaction_deltaA.png")

    summary["single_vsc"] = {
        "with_feedforward_escaped": bool(res_ff["escaped"]),
        "without_feedforward_escaped": bool(res_noff["escaped"]),
        "with_feedforward_max_abs_deltaA_over_A": float(
            np.max(np.abs(res_ff["delta_A"][:, 0] / p.A))
        ),
        "without_feedforward_max_abs_deltaA_over_A": float(
            np.max(np.abs(res_noff["delta_A"][:, 0] / p.A))
        ),
    }

    # 3) Two identical VSCs: static device coupling approximately 0.75 A1.
    two = FullMultiVSC(2)
    two.voltage_feedforward[:] = 1.0
    res_deep = two.simulate_fault(depth=0.5, duration=0.04)
    res_shallow = two.simulate_fault(depth=0.7, duration=0.02)

    B_over_A = (
        (two.Rg * two.iq_ref[1] + two.Lg * two.omega0 * two.id_ref[1])
        / p.A
    )
    static_scale = 1.0 + B_over_A
    m_two = FuReducedModel(
        p=p,
        static_scale=static_scale,
        dynamic_bound_scale=0.1,
        b1=p.B1_identical_neighbor,
    )
    fig, ax = plt.subplots()
    phase_background(ax, m_two)
    ax.plot(
        res_deep["x"][1, :],
        res_deep["omega"][:, 0],
        label="50% voltage, 0.04 s",
    )
    ax.plot(
        res_shallow["x"][1, :],
        res_shallow["omega"][:, 0],
        label="70% voltage, 0.02 s",
    )
    ax.set_title("Static interaction from a parallel VSC changes the phase-plane margin")
    ax.legend()
    save_fig(fig, "04_two_vsc_static_coupling_phase.png")

    summary["two_identical_vsc"] = {
        "B_over_A": float(B_over_A),
        "static_scale_A_plus_B_over_A": float(static_scale),
        "deep_fault_escaped": bool(res_deep["escaped"]),
        "shallower_fault_escaped": bool(res_shallow["escaped"]),
    }

    # 4) A mismatched neighbor produces a nonzero Delta B path.
    mismatch = FullMultiVSC(2)
    mismatch.voltage_feedforward[:] = 1.0
    mismatch.id_ref[1] = 60.0
    mismatch.Li[1] = 6e-3
    res_mismatch = mismatch.simulate_fault(depth=0.7, duration=0.02)

    fig, ax = plt.subplots()
    ax.plot(
        res_mismatch["t"],
        res_mismatch["delta_B"][:, 0] / p.A,
        label=r"$\Delta B_1/A_1$",
    )
    ax.axhline(0.0, linewidth=0.8)
    ax.set_xlabel("time [s]")
    ax.set_ylabel("normalized interaction")
    ax.set_title("Dynamic device-to-device interaction caused by asynchronous trajectories")
    ax.legend()
    save_fig(fig, "05_device_dynamic_interaction_deltaB.png")

    summary["mismatched_neighbor"] = {
        "max_abs_deltaB1_over_A1": float(
            np.max(np.abs(res_mismatch["delta_B"][:, 0] / p.A))
        ),
        "escaped": bool(res_mismatch["escaped"]),
    }

    # 5) Path dependence: same projected (delta, omega), different hidden residual.
    m_path = FuReducedModel(
        p=p,
        static_scale=1.5,
        dynamic_bound_scale=0.5,
        b1=p.B1_identical_neighbor,
    )
    common_delta0 = 2.30
    common_omega0 = 0.0
    path_inject = m_path.simulate_hidden_path(
        common_delta0, common_omega0, +0.5 * p.A, 0.0
    )
    path_absorb = m_path.simulate_hidden_path(
        common_delta0, common_omega0, -0.5 * p.A, 0.0
    )

    fig, ax = plt.subplots()
    phase_background(ax, m_path)
    ax.plot(path_inject.y[0, :], path_inject.y[1, :], label="hidden residual injects energy")
    ax.plot(path_absorb.y[0, :], path_absorb.y[1, :], label="hidden residual absorbs energy")
    ax.scatter([common_delta0], [common_omega0], marker="x", s=48)
    ax.annotate(
        "same projected initial point",
        (common_delta0, common_omega0),
        xytext=(-95, 18),
        textcoords="offset points",
        arrowprops={"arrowstyle": "->"},
    )
    ax.set_title("Path dependence after projecting hidden current/neighbor states")
    ax.legend()
    save_fig(fig, "06_projected_path_dependence.png")

    summary["path_dependence"] = {
        "common_delta0": common_delta0,
        "common_omega0": common_omega0,
        "positive_hidden_residual_escaped": bool(
            path_inject.t_events and len(path_inject.t_events[0]) > 0
        ),
        "negative_hidden_residual_escaped": bool(
            path_absorb.t_events and len(path_absorb.t_events[0]) > 0
        ),
    }

    (OUT / "summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    run()
